version: "3.4"

services:
  main:
    build:
      context: '../../.'
      target: 'tester-shell-environment'
      args:
        DESIRED_WP_VERSION: "${WP_VERSION}"
        DESIRED_PHP_VERSION: "${PHP_VERSION}"
        CONTAINER_USER_ID: "${CONTAINER_USER_ID}"
        CONTAINER_GROUP_ID: "${CONTAINER_GROUP_ID}"
    image: 'tester-shell-cache'
    container_name: 'wp-graphql'
    environment:
      DB_SERVE_NAME: 'wpgraphql_test'
      DB_HOST: 'mysql_test'
      DB_USER: 'root'
      DB_PASSWORD: 'testing'
    volumes:
      # Using "delegated" option to improve disk performance for "Docker for Mac" users:
      # https://docs.docker.com/docker-for-mac/osxfs-caching/#delegated
      - "${PWD}:/project:delegated"
    entrypoint:
      # Doing this to prevent the container exiting prematurely. This service needs to hang around for someone to access
      # its shell.
      [ "sleep", "9999d" ]

  wpgraphql.test:
    build:
      context: '../../.'
      target: 'wordpress-sut-environment'
      args:
        DESIRED_WP_VERSION: "${WP_VERSION}"
        DESIRED_PHP_VERSION: "${PHP_VERSION}"
    image: 'wordpress-sut-cache'
    environment:
      WORDPRESS_DB_HOST: 'mysql_test'
      WORDPRESS_DB_NAME: 'wpgraphql_test'
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'testing'

  mysql_test:
    image: "${MYSQL_DOCKER_IMAGE}"
    environment:
      MYSQL_DATABASE: 'wpgraphql_test'
      MYSQL_ROOT_PASSWORD: 'testing'
