version: "3.4"

services:
  main:
    build:
      context: '../..'
      target: 'tester-shell'
      args:
        DESIRED_WP_VERSION: "${WP_VERSION}"
        DESIRED_PHP_VERSION: "${PHP_VERSION}"
    image: 'tester-shell-cache'
    container_name: 'wp-graphql'
    environment:
      DB_SERVE_NAME: 'wpgraphql_test'
      DB_HOST: 'mysql_test'
      DB_USER: 'root'
      DB_PASSWORD: 'testing'
    volumes:
      # Using "delegated" option to improve disk performance for "Docker for Mac" users:
      # https://docs.docker.com/docker-for-mac/osxfs-caching/#delegated
      - "${PWD}:/project:delegated"

  wpgraphql.test:
    image: "wordpress:${WP_VERSION}-php${PHP_VERSION}-apache"
    environment:
      WORDPRESS_DB_HOST: 'mysql_test'
      WORDPRESS_DB_NAME: 'wpgraphql_test'
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'testing'
    volumes:
    - "${PWD}:/var/www/html/wp-content/plugins/wp-graphql:ro"

  mysql_test:
    image: "${MYSQL_DOCKER_IMAGE}"
    environment:
      MYSQL_DATABASE: 'wpgraphql_test'
      MYSQL_ROOT_PASSWORD: 'testing'
