version: "3"

services:
  wpgraphql.test:
    build:
      context: ../../.
      args:
        WP_DOCKER_IMAGE: "wordpress:${WP_VERSION:-4.9.8}-php${PHP_VERSION:-7.2}-apache"
    image: wpgraphql-cache
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: 'mysql_test'
      WORDPRESS_DB_NAME: 'wpgraphql_test'
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'testing'
    entrypoint:
      [ "docker-entrypoint.wpgraphql.sh" ]

  mysql_test:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: 'wpgraphql_test'
      MYSQL_ROOT_PASSWORD: 'testing'
