version: "3.4"

services:
  wpgraphql.test:
    image: "wordpress:${WP_VERSION:-5.2.2}-php${PHP_VERSION:-7.3}-apache"
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST: 'mysql_test'
      WORDPRESS_DB_NAME: 'wpgraphql_test'
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'testing'
    volumes:
      - '../:/var/www/html/wp-content/plugins/wp-graphql:ro'

      # For file-specific bind mounts, file changes outside of the container will not be automatically propagated
      # inside the container. This particular file probably won't change very often, so this bind mount is probably fine.
      # Please see this for more information: https://github.com/moby/moby/issues/15793#issuecomment-453435094
      - './uploads.txt:/usr/local/etc/php/conf.d/uploads.ini:ro'

  mysql_test:
    image: 'mariadb:10.2.26-bionic'
    ports:
      # Have Docker forward a randomly assigned host port to this site's MySQL container port
      - '3306'
    environment:
      MYSQL_DATABASE: 'wpgraphql_test'
      MYSQL_ROOT_PASSWORD: 'testing'
